version: 2.1

orbs:
  python: circleci/python@1.3.4

workflows:
  main:
    jobs:
      - python/test:
          version: "3.6"
      - python/test:
          version: "3.7"
      - python/test:
          version: "3.8"